### ISSUE TITLE
Tabbar onPreChange event

### ISSUE THREAD

**Issue by mbessieres** [snipking/react-onsenui-types-hotfix#1]
Thanks for making these fixes! Any reason you're not doing pull requests to the DefinitelyTyped repo to get it into the standard type definitions?

I think you're now out of date with the latest Tabbar onPreChange which includes a property for lastActiveIndex. See the code for the swiper (which Tabbar uses and handles the event hooks):

https://github.com/OnsenUI/OnsenUI/blob/a95d7e259fd288e05a3de4bd2f3a0f1d94852bfc/core/src/ons/internal/swiper.js#L333

**Comment by snipking** [comment]
Today the react-onsenui type define in DefinitelyTyped is better than the old time. We making these hot fixes to fit our working project. Today maybe it is unnecessary.

BTW the activeIndex and lastActiveIndex is working for onPreChange. But not included in onsenui 2 document. We making this hot fix project base on it.

Also PRs Welcome.

**Comment by mbessieres** [comment]
Got it... thanks! Yeah I was trying to compare between the @types/react-onsenui and yours which has some newer commits. They're both a little off in their owns ways thanks to onsenui's documentation being absolutely horrible and also out of date. Appreciate the fix!
